### ISSUE TITLE
Build error caused by IS_J9_OBJECT_MONITOR_OWNER_DETACHED()

### ISSUE THREAD

**Issue by knn-k** [eclipse-openj9/openj9#21761]
Building OpenJ9 Java 17 (and older) fails with the following error:

```
/home/openj9/openj9-openjdk-jdk17/openj9/runtime/util/moninfo.c: In function 'getObjectMonitorOwner':
/home/openj9/openj9-openjdk-jdk17/openj9/runtime/util/moninfo.c:89:38: error: implicit declaration of function 'IS_J9_OBJECT_MONITOR_OWNER_DETACHED'; did you mean 'J9_OBJECT_MONITOR_ENTER_FAILED'? [-Werror=implicit-function-declaration]
   89 |                                 if (!IS_J9_OBJECT_MONITOR_OWNER_DETACHED(osOwner)) {
      |                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                      J9_OBJECT_MONITOR_ENTER_FAILED
```

The macro was introduced by PR #21728, and the macro is defined only for Java 19 and above.

**Comment by knn-k** [comment]
I can build OpenJ9 Java 17 by adding the following lines to runtime/oti/j9nonbuilder.h, but I am not sure if that is the correct fix or not:

```
        struct J9VMThread* previousOwner;
 #endif /* JAVA_SPEC_VERSION >= 24 */
 } J9VMContinuation;
+#else /* JAVA_SPEC_VERSION >= 19 */
+#define IS_J9_OBJECT_MONITOR_OWNER_DETACHED(owner) FALSE
 #endif /* JAVA_SPEC_VERSION >= 19 */

 /* @ddr_namespace: map_to_type=J9VMThread */
```

**Comment by babsingh** [comment]
fyi @hangshao0
