### ISSUE TITLE
jdk19 failing to compile

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#14404]
https://openj9-jenkins.osuosl.org/job/Pipeline-OpenJDK-Acceptance/221/

https://github.com/ibmruntimes/openj9-openjdk-jdk/compare/661ba3c8f01...b90944f187b

Guessing this is caused by https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/68c2fa0344f4bcc695042f01473d490db9b44340 "8280534: Enable compile-time doclint reference checking"
```
02:56:51  /home/jenkins/workspace/Build_JDKnext_aarch64_linux_OpenJDK/build/linux-aarch64-server-release/support/j9jcl/java.management/share/classes/java/lang/management/PlatformLoggingMXBean.java:49: error: reference not found
02:56:51  	 * Returns the string name of the specified {@link java.util.logging.Logger} instance's
02:56:51  	                                                   ^
02:56:51  /home/jenkins/workspace/Build_JDKnext_aarch64_linux_OpenJDK/build/linux-aarch64-server-release/support/j9jcl/java.management/share/classes/java/lang/management/PlatformLoggingMXBean.java:73: error: reference not found
02:56:51  	 * Returns the name of the parent {@link java.util.logging.Logger} of the specified registered
02:56:51  	                                         ^
02:56:51  /home/jenkins/workspace/Build_JDKnext_aarch64_linux_OpenJDK/build/linux-aarch64-server-release/support/j9jcl/java.management/share/classes/java/lang/management/PlatformLoggingMXBean.java:90: error: reference not found
02:56:51  	 * Attempts to update the log level of the {@link java.util.logging.Logger} with name 
02:56:51  	                                                  ^
02:56:51  /home/jenkins/workspace/Build_JDKnext_aarch64_linux_OpenJDK/build/linux-aarch64-server-release/support/j9jcl/java.management/share/classes/java/lang/management/PlatformLoggingMXBean.java:106: error: reference not found
02:56:51  	 * the caller does not have {@link java.util.logging.LoggingPermission} of &quot;control&quot;.
```

@JasonFengJ9 @keithc-ca
