### PR TITLE
Remove duplicate typedef in tests downcall.h

### PR DESCRIPTION
**Pull request by pshipton**
The following dup is removed:
typedef struct stru_Byte_Byte_Byte stru_Byte_Byte_Byte;

It fails to compile on the latest xlC 16.1.0.7 on AIX.

### CODE REVIEW

**Comment by pshipton** [comment]
@ChengJin01 fyi

**Comment by pshipton** [comment]
fyi testing is done internally at /view/OpenJ9%20-%20Personal/job/Pipeline-Build-Test-Personal/13060/
Without this change the compile failed.
Related to updating the xlC version runtimes/infrastructure/issues/6768#issuecomment-44319561
```
18:00:44  /home/jenkins/workspace/Build_JDK11_ppc64_aix_Personal/openj9/runtime/tests/clinkerffi/downcall.h:54:36: error: redefinition of typedef 'stru_Byte_Byte_Byte' is a C11 feature [-Werror,-Wtypedef-redefinition]
18:00:44  typedef struct stru_Byte_Byte_Byte stru_Byte_Byte_Byte;
18:00:44                                     ^
18:00:44  /home/jenkins/workspace/Build_JDK11_ppc64_aix_Personal/openj9/runtime/tests/clinkerffi/downcall.h:47:36: note: previous definition is here
18:00:44  typedef struct stru_Byte_Byte_Byte stru_Byte_Byte_Byte;
18:00:44                                     ^
18:00:44  1 error generated.
18:00:44  Error while processing /home/jenkins/workspace/Build_JDK11_ppc64_aix_Personal/openj9/runtime/tests/clinkerffi/downcall.c.
```

File: runtime/tests/clinkerffi/downcall.h [hunk 1]
```diff
@@ -51,7 +51,6 @@ typedef struct stru_NestedByteArray_Byte stru_NestedByteArray_Byte;
 typedef struct stru_Byte_NestedByteArray stru_Byte_NestedByteArray;
 typedef struct stru_NestedStruArray_Byte stru_NestedStruArray_Byte;
 typedef struct stru_Byte_NestedStruArray stru_Byte_NestedStruArray;
-typedef struct stru_Byte_Byte_Byte stru_Byte_Byte_Byte;
```
[the remark this answers is not in the document]
Comment (pshipton) [reply runtime/tests/clinkerffi/downcall.h:54]: I'm not planning to do that. @ChengJin01 could elect to do this in another PR.

[the remark this answers is not in the document]
Comment (keithc-ca) [reply runtime/tests/clinkerffi/downcall.h:54]: I didn't think it was asking too much, but I agree the more pressing matter is fixing the compile error.

**Review by keithc-ca — APPROVED** [review]

**Comment by keithc-ca** [comment]
Tested change locally as well.
