### PR TITLE
Pass VENDOR_CODE parameters to build jobs

### PR DESCRIPTION
**Pull request by pshipton**
Depends on https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/838

### CODE REVIEW

**Comment by pshipton** [comment]
jenkins compile zlinux jdk8 depends ibmruntimes/openj9-openjdk-jdk8#838

**Comment by pshipton** [comment]
jenkins compile amac jdk11

**Comment by pshipton** [comment]
jenkins compile zlinux jdk8 depends https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/838

File: buildenv/jenkins/common/build.groovy [hunk 1]
```diff
@@ -37,9 +37,18 @@ def get_source() {
...
 
+        VENDOR_CODE_REPO_OPTION = (VENDOR_CODE_REPO != "") ? "-vendor-code-repo=${VENDOR_CODE_REPO}" : ""
+        VENDOR_CODE_BRANCH_OPTION = (VENDOR_CODE_BRANCH != "") ? "-vendor-code-branch=${VENDOR_CODE_BRANCH}" : ""
+        VENDOR_CODE_SHA_OPTION = (VENDOR_CODE_SHA != "") ? "-vendor-code-sha=${VENDOR_CODE_SHA}" : ""
+
         if (OPENJDK_REFERENCE_REPO) {
             OPENJ9_REFERENCE = "-openj9-reference=${OPENJDK_REFERENCE_REPO}"
             OMR_REFERENCE = "-omr-reference=${OPENJDK_REFERENCE_REPO}"
+            if (SDK_VERSION == "8" || SPEC.contains('zos')) {
+                VENDOR_CODE_REFERENCE = "-vendor-code-reference=${OPENJDK_REFERENCE_REPO}"
```
Comment (keithc-ca) [inline buildenv/jenkins/common/build.groovy]: Is `OPENJDK_REFERENCE_REPO` a cache for everything?

**Comment by keithc-ca** [comment]
> 11:10:18  Unknown option: '-vendor-code-reference=/home/jenkins/openjdk_cache'

The extensions repos need to be taught the new options, or that one should only be added if one of the other "vendor-code" options is needed.

File: buildenv/jenkins/common/build.groovy (hunk 1 above)
Comment (pshipton) [reply buildenv/jenkins/common/build.groovy]: yes

**Comment by pshipton** [comment]
jenkins compile plinux jdk8 depends https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/838

**Comment by pshipton** [comment]
> The extensions repos need to be taught the new options, or that one should only be added if one of the other "vendor-code" options is needed.

I'm aware, see https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/838

`vendor-code` isn't a good name, `vendor_code` would work, but I decided `vendor` is consistent with https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/1031, if you agree.

**Comment by pshipton** [comment]
jenkins compile amac jdk11

**Comment by pshipton** [comment]
The amac compilation error is unrelated, caused by https://github.com/eclipse-openj9/openj9/pull/22003

File: buildenv/jenkins/common/build.groovy [hunk 2]
```diff
@@ -37,9 +37,18 @@ def get_source() {
...
 
+        VENDOR_CODE_REPO_OPTION = (VENDOR_CODE_REPO != "") ? "-vendor-repo=${VENDOR_CODE_REPO}" : ""
+        VENDOR_CODE_BRANCH_OPTION = (VENDOR_CODE_BRANCH != "") ? "-vendor-branch=${VENDOR_CODE_BRANCH}" : ""
+        VENDOR_CODE_SHA_OPTION = (VENDOR_CODE_SHA != "") ? "-vendor-sha=${VENDOR_CODE_SHA}" : ""
+
         if (OPENJDK_REFERENCE_REPO) {
             OPENJ9_REFERENCE = "-openj9-reference=${OPENJDK_REFERENCE_REPO}"
             OMR_REFERENCE = "-omr-reference=${OPENJDK_REFERENCE_REPO}"
+            if (SDK_VERSION == "8" || SPEC.contains('zos')) {
+                VENDOR_CODE_REFERENCE = "-vendor-reference=${OPENJDK_REFERENCE_REPO}"
```
Comment (keithc-ca) [inline buildenv/jenkins/common/build.groovy:48]: The point I tried make earlier was that line 48 should not execute unless both `VENDOR_CODE_REPO` and `VENDOR_CODE_BRANCH` are set.

Comment (pshipton) [reply buildenv/jenkins/common/build.groovy:48]: I don't think it's that simple. They don't need to be set, but there could be a default repo/branch set in the get_source.sh and we still want to use a reference repo.

File: buildenv/jenkins/common/build.groovy (hunk 1 above)
Comment (keithc-ca) [reply buildenv/jenkins/common/build.groovy]: This depends on changes to the z/OS repositories so they understand `-vendor-code-reference=`.

File: buildenv/jenkins/common/build.groovy (hunk 2 above)
Comment (keithc-ca) [reply buildenv/jenkins/common/build.groovy:48]: You're right: I neglected to consider defaults.

File: buildenv/jenkins/common/build.groovy (hunk 1 above)
Comment (pshipton) [reply buildenv/jenkins/common/build.groovy]: What's shown here is outdated, it's using `-vendor-reference=` if you look at the latest changes.
