### ISSUE TITLE
Build failure: 'MM_MemorySubSpaceTarok::reset' hides overloaded virtual function

### ISSUE THREAD

**Issue by ymanton** [eclipse-openj9/openj9#24156]
OpenJ9 fails to build with https://github.com/eclipse-openj9/openj9-omr/commit/7f732bfe8d9b113c07e0faf0aac482dc65c4e9f1. Build error is:

```
07:59:19  In file included from /Users/jenkins/workspace/Build_JDK17_aarch64_mac_OMR/openj9/runtime/gc_vlhgc/AllocationContextBalanced.cpp:41:
07:59:19  /Users/jenkins/workspace/Build_JDK17_aarch64_mac_OMR/openj9/runtime/gc_vlhgc/MemorySubSpaceTarok.hpp:250:15: error: 'MM_MemorySubSpaceTarok::reset' hides overloaded virtual function [-Werror,-Woverloaded-virtual]
07:59:19          virtual void reset();
07:59:19                       ^
07:59:19  /Users/jenkins/workspace/Build_JDK17_aarch64_mac_OMR/omr/gc/base/MemorySubSpace.hpp:346:15: note: hidden overloaded virtual function 'MM_MemorySubSpace::reset' declared here: different number of parameters (1 vs 0)
07:59:19          virtual void reset(MM_EnvironmentBase *env = NULL);
07:59:19                       ^
```

Fails on aarch64 Linux JDK8 (but not 11, 17, 21), aarch64 Mac JDK 11, 17, 21, x86-64 Mac JDK 8, 11, 17, 21. 

I suspect the problem is with https://github.com/eclipse-omr/omr/pull/8284, FYI @amicic.

**Comment by ymanton** [comment]
Reference output:

https://openj9-jenkins.osuosl.org/job/Build_JDK17_aarch64_mac_OMR/739/consoleText
https://openj9-jenkins.osuosl.org/job/Build_JDK8_aarch64_linux_OMR/863/consoleText

**Comment by amicic** [comment]
personal build that confirms the OpenJ9 PR fixes the problem (amac java11 specifically)

https://hyc-runtimes-jenkins.swg-devops.com/view/OpenJ9%20-%20Personal/job/Pipeline-Build-Test-Personal/33984/
(IBM internal jenkins farm)

(the build included the offending OMR change)
