### PR TITLE
Do not call getVMThreadFromOMRThread() if monitor owner is detached

### LINKED ISSUE #21761: Build error caused by IS_J9_OBJECT_MONITOR_OWNER_DETACHED()
Building OpenJ9 Java 17 (and older) fails with the following error:

```
/home/openj9/openj9-openjdk-jdk17/openj9/runtime/util/moninfo.c: In function 'getObjectMonitorOwner':
/home/openj9/openj9-openjdk-jdk17/openj9/runtime/util/moninfo.c:89:38: error: implicit declaration of function 'IS_J9_OBJECT_MONITOR_OWNER_DETACHED'; did you mean 'J9_OBJECT_MONITOR_ENTER_FAILED'? [-Werror=implicit-function-declaration]
   89 |                                 if (!IS_J9_OBJECT_MONITOR_OWNER_DETACHED(osOwner)) {
      |                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                      J9_OBJECT_MONITOR_ENTER_FAILED
```

The macro was introduced by PR #21728, and the macro is defined only for Java 19 and above.

### PR DESCRIPTION
**Pull request by hangshao0**
Monitor owner is set to 1 if the virtual thread is detached. Add a new
macro for that. getVMThreadFromOMRThread() should only be called if the
owner is a valid omr thread.

Closes #21761

### CODE REVIEW

**Comment by hangshao0** [comment]
> the commits can be squashed.

Yes, I put it as a separate commit so that is easier for reviewer to review. I can squash it once it it approved.

**Comment by babsingh** [comment]
lgtm as a code change. i will formally approve it after the PR builds pass. o am about to launch the PR builds for validation. if the changes are squashed after the builds are launched, the PR build links will need to be manually found and posted. you can squash the commits now to prevent this issue.

**Comment by babsingh** [comment]
jenkins test sanity amac jdk24

**Comment by babsingh** [comment]
jenkins compile alinux jdk17

**Comment by babsingh** [comment]
jenkins compile zlinux jdk21

**Review by babsingh — APPROVED** [review]
