### ISSUE TITLE
OpenJDK-Acceptance build is failing on Windows

### ISSUE THREAD

**Issue by keithc-ca** [eclipse-openj9/openj9#22898]
First seen in https://openj9-jenkins.osuosl.org/job/Build_JDKnext_x86-64_windows_OpenJDK/894:
```
[2025-11-06T05:40:26.317Z] /cygdrive/f/Users/jenkins/workspace/Build_JDKnext_x86-64_windows_OpenJDK/make/scripts/fixpath.sh: line 445: 46822 Segmentation fault      "$command" "${collected_args[@]}"
[2025-11-06T05:40:26.848Z] f:\Users\jenkins\workspace\Build_JDKnext_x86-64_windows_OpenJDK\test\jdk\java\foreign\sharedclosejvmti\libSharedCloseAgent.cpp(105): fatal error C1001: Internal compiler error.
[2025-11-06T05:40:26.848Z] (compiler file 'msc1.cpp', line 1693)
[2025-11-06T05:40:26.848Z]  To work around this problem, try simplifying or changing the program near the locations listed above.
[2025-11-06T05:40:26.848Z] If possible please provide a repro here: https://developercommunity.visualstudio.com 
[2025-11-06T05:40:26.848Z] Please choose the Technical Support command on the Visual C++ 
[2025-11-06T05:40:26.848Z]  Help menu, or open the Technical Support help file for more information
[2025-11-06T05:40:26.848Z] INTERNAL COMPILER ERROR in 'C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\bin\Hostx64\x64\cl.exe'
[2025-11-06T05:40:26.848Z]     Please choose the Technical Support command on the Visual C++
[2025-11-06T05:40:26.848Z]     Help menu, or open the Technical Support help file for more information
[2025-11-06T05:40:26.848Z] make[3]: *** [test/JtregNativeJdk.gmk:137: /cygdrive/f/Users/jenkins/workspace/Build_JDKnext_x86-64_windows_OpenJDK/build/windows-x86_64-server-release/support/test/jdk/jtreg/native/support/libSharedCloseAgent/libSharedCloseAgent.obj] Error 1
```
I thought it might be an intermittent or infrastructure problem but it failed the same way on restart in https://openj9-jenkins.osuosl.org/job/Build_JDKnext_x86-64_windows_OpenJDK/895.

**Comment by keithc-ca** [comment]
The failing builds are using `microsoft C compiler version 19.32.31329` while a local build with `microsoft C compiler version 19.33.31629` works. It would seem we should update our build machines.

**Comment by keithc-ca** [comment]
Testing a workaround in https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/1129.

**Comment by keithc-ca** [comment]
An upstream change has been merged into the head stream:
* [8371871: libSharedCloseAgent.cpp crashes VS2019 and older VS2022 compiler](https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/23abf83154389a78bc67be663538b210bbe251a0)

I expect that change to flow into jdk26 after which we can close this.
