### ISSUE TITLE
Latest openJ9 JDK11 loads a class from wrong location on modular run

### ISSUE THREAD

**Issue by andresluuk** [eclipse-openj9/openj9#14975]
Java -version output
--------------------
openjdk version "11.0.15" 2022-04-19
IBM Semeru Runtime Open Edition 11.0.15.0 (build 11.0.15+10)
Eclipse OpenJ9 VM 11.0.15.0 (build openj9-0.32.0, JRE 11 Windows 10 amd64-64-Bit Compressed References 20220422_352 (JIT enabled, AOT enabled)
OpenJ9   - 9a84ec34e
OMR      - ab24b6666
JCL      - b7b5b42ea6 based on jdk-11.0.15+10)
Does not matter if windows or linux.

Summary of problem
------------------
I noticed a bug/issue on the latest OpenJDK 11.0.15+10 OpenJ9 0.32.0 (It was not there in the previous release, and not on the normal JDK11-s).
If I have an application with a custom classloader (I have given it null as the parent classloader) and try to load a class from it (that also exists in the normal classpath):
Class k = Class.forName("autotest.TargetUnver", true, new MyCustomClassLoader());
I will get on normal JDK and previous versions and current openJDK 11 with classpath run:
TargetUnver has classLoader autotest.MyCustomClassLoader@22a71081
But if I run the application as a modular application with module path, open latest openJDK 11 I will get:
TargetUnver has classLoader jdk.internal.loader.ClassLoaders$AppClassLoader@4418b527
This issue happens only in the latest OpenJDK11 with modular run.

Diagnostic files
----------------
I made a simple app to showcase the issue.
If you run it with classpath, all ok:
java -cp target\MyJar.jar autotest.Test
But the modular run gets a different result for some reason (does not happen on openJDK or older versions):
java --module-path target\MyJar.jar -m MyJar/autotest.Test
[simple-java-maven-app-master.zip](https://github.com/eclipse-openj9/openj9/files/8582875/simple-java-maven-app-master.zip)

**Comment by pshipton** [comment]
@tajila

**Comment by keithc-ca** [comment]
Tweaking the example a little (to use try-with-resources), yields a possible hint:
```
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/keithc/space/openj9/issue-14975/src/main/java/autotest/CustomClassLoader.java:[31,21] try-with-resources is not supported in -source 6
  (use -source 7 or higher to enable try-with-resources)
```
I don't see anything in `pom.xml` that says `-source 6`: perhaps specifying `-source 11 -target 11` (or newer) in the appropriate places would solve this?

**Comment by keithc-ca** [comment]
Adding to `pom.xml`
```
	<configuration>
		<release>11</release>
	</configuration>
```
allows the build to succeed, but it doesn't define a module named `MyJar`; we need `module-info.java` for that, after which I see the problem: it works with 0.30.0, but not with 0.32.0 or a development build.

**Comment by andresluuk** [comment]
Great that you reproduced it.
I did't include the jdk version in pom. Because with JDK11 on path, "mvn clean package" worked.
About module-info.java I used the automatic module: java --module-path target\MyJar.jar -m MyJar/autotest.Test
just in case module-info would break something in classpath run (java -cp target\MyJar.jar autotest.Test) where no modules are present, but good that you also managed to reproduce it with module-info.java

**Comment by DanHeidinga** [comment]
Adding a Blocker tag to this as per Keith's comment, this is a regression from 0.30 -> 0.32

**Comment by tajila** [comment]
Ill take a look

**Comment by tajila** [comment]
I suspect this is the cause, https://github.com/eclipse-openj9/openj9/pull/14689

**Comment by tajila** [comment]
Confirmed that https://github.com/eclipse-openj9/openj9/pull/14689 causes this regression

@JasonFengJ9 Can you please take a look
