### PR TITLE
Fix build break in JDK8,11 due to undefined targetMethodFromMemberName

### PR DESCRIPTION
**Pull request by dsouzai**
This PR fixes a build break in JDK8 and JDK11 introduced by https://github.com/eclipse-openj9/openj9/pull/20373 which occurred because `J9VM_OPT_OPENJDK_METHODHANDLE` is not defined.

### CODE REVIEW

**Comment by dsouzai** [comment]
jenkins compile xlinux jdk8,jdk11,jdk17

**Review by jdmpapin — APPROVED** [review]

**Comment by keithc-ca** [comment]
This needs more work; trying to build jdk11:
```
/home/keithc/space/openj9/jdk11/openj9/runtime/compiler/runtime/SymbolValidationManager.cpp:1591:18: error: 'class TR_J9VM' has no member named 'isInvokeCacheEntryAnArray'
       if (_fej9->isInvokeCacheEntryAnArray(invokeCacheArray))
                  ^~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by dsouzai** [comment]
Ok, built both JDK11 and JDK21 manually and both passed, so should be good to go now.

**Comment by pshipton** [comment]
jenkins compile zlinux jdk8

**Review by pshipton — APPROVED** [review]
