### ISSUE TITLE
May need to use newer version of macOS SDK to build JDK22+

### ISSUE THREAD

**Issue by keithc-ca** [eclipse-openj9/openj9#18334]
https://openj9-jenkins.osuosl.org/job/Build_JDKnext_x86-64_mac_OpenJDK/539/consoleText says
```
[2023-10-23T17:24:32.376Z] checking for sysroot... /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk
```
and later
```
[2023-10-23T17:43:26.599Z] /Users/jenkins/workspace/Build_JDKnext_x86-64_mac_OpenJDK/src/java.desktop/macosx/native/libawt_lwawt/awt/CGraphicsDevice.m:69:29: error: use of undeclared identifier 'NSBundleExecutableArchitectureARM64'; did you mean 'NSBundleExecutableArchitecturePPC64'?
[2023-10-23T17:43:26.600Z]         if (architecture == NSBundleExecutableArchitectureARM64) {
[2023-10-23T17:43:26.600Z]                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[2023-10-23T17:43:26.600Z]                             NSBundleExecutableArchitecturePPC64
```
[8317970: Bump target macosx-x64 version to 11.00.00](https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/ec1f6fe42506a298f6f2385609583f14b6de2e57) changed `flags.m4` to say
```
    MACOSX_VERSION_MIN=11.00.00
```
Perhaps we need to upgrade the macOS build systems to use a new MacOSX SDK?

**Comment by pshipton** [comment]
OpenJ9 already builds jdk11+ with xcode 13.0 and clang 13.0.0.

**Comment by pshipton** [comment]
Sorry, that was aarch64.

For x64, we already build with xcode 12.4 and clang 12.0.0.

**Comment by keithc-ca** [comment]
I updated the title: this is less about the version of Xcode and more (I think) about the version of the macOS SDK.

**Comment by pshipton** [comment]
Ah ok. We could try a build on https://openj9-jenkins.osuosl.org/computer/mac13%2Dx86%2D5/

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-Personal/435/

**Comment by pshipton** [comment]
I had 13 on the brain. Try again on OS 11.
https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-Personal/436/

**Comment by pshipton** [comment]
The build on OS 13 still seg faults (https://openj9-jenkins.osuosl.org/job/Build_JDKnext_x86-64_mac_Personal/34), so likely the build on OS 11 will do the same.

**Comment by keithc-ca** [comment]
Another option would be to (temporarily) revert the change in `CGraphicsDevice.m`. Opinions?

**Comment by pshipton** [comment]
> Another option would be to (temporarily) revert the change in CGraphicsDevice.m

Sounds like a plan.

**Comment by keithc-ca** [comment]
See https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/681, which should be reverted before this is closed.

**Comment by pshipton** [comment]
This may just be a bad machine setup, see https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/681#issuecomment-1777991741

**Comment by keithc-ca** [comment]
Has [mac10-x86-3](https://openj9-jenkins.osuosl.org/computer/mac10-x86-3) been updated or corrected, or have we just been lucky that it hasn't been used for jdk22 builds recently?

**Comment by pshipton** [comment]
I opened an infra issue to fix it and removed the ci.role.build label so it's not used until it gets fixed.

**Comment by pshipton** [comment]
I think we can close this, the build machines should have sdk 11, it's an infra issue that mac10-x86-3 recently re-built didn't have the correct sdk. I didn't check them all but another pops up we know how to fix it.

**Comment by keithc-ca** [comment]
> we can close this

Agreed.
