### ISSUE TITLE
Compile error in ObjectMonitor.cpp

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#16818]
This is from an internal build. Compilation is failing on jdk8 at least xlinux and zlinux due to https://github.com/eclipse-openj9/openj9/pull/16812. I expect it will fail on other versions for non-xlinux as well.
```
ObjectMonitor.cpp: In function 'UDATA objectMonitorEnterNonBlocking(J9VMThread*, j9object_t)':
ObjectMonitor.cpp:319:10: error: unused variable 'retry' [-Werror=unused-variable]
  BOOLEAN retry = FALSE;
          ^~~~~
```
